export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_ORDER_QTY = "ADJUST_TO_QTY";
export const ADJUST_ORDER_OPTION = "ADJUST_ITEM_OPTION";
export const LOAD_CURRENT_ORDER = "LOAD_CURRENT_ORDER";
